services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./settings.js:/usr/share/nginx/html/scripts/settings.js
    depends_on:
      - geoportal-connect

  geoportal-connect:
    container_name: geoportal-connect
    image: nodered/node-red
    environment:
      - WEBSOCKET_HOST=connect.staging.gebatrans.app
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data